# P.E.P.P.E.R. Project Configuration

version:
  major: 1
  minor: 0
  patch: 0

# Agent configurations
agents:
  frontend_agent:
    type: "frontend"
    capabilities:
      - component_creation
      - styling
      - state_management
    retry:
      retries: 3
      delay: 1.0
      max_delay: 32.0
      backoff_strategy: "exponential"
      
  backend_agent:
    type: "backend"
    capabilities:
      - api_development
      - database_integration
      - authentication
    retry:
      retries: 3
      delay: 1.0
      max_delay: 32.0
      backoff_strategy: "exponential"
      
  qa_agent:
    type: "qa"
    capabilities:
      - api_testing
      - component_testing
      - performance_testing
    retry:
      retries: 2
      delay: 1.0
      max_delay: 16.0
      backoff_strategy: "linear"
      
  pm_agent:
    type: "pm"
    capabilities:
      - task_prioritization
      - dependency_management
      - progress_tracking
    retry:
      retries: 1
      delay: 1.0
      max_delay: 8.0
      backoff_strategy: "fixed"

# Task definitions with priorities and dependencies
tasks:
  # Backend API Development
  - id: "build_api"
    agent: "backend_agent"
    task: "Create FastAPI endpoint for job listings"
    priority: "HIGH"
    metadata:
      endpoint: "/api/jobs"
      method: "GET"
      response_format: "json"
      
  - id: "validate_api"
    agent: "qa_agent"
    task: "qa.backend_validation"
    depends_on: ["build_api"]
    priority: "MEDIUM"
    metadata:
      test_type: "integration"
      endpoint: "/api/jobs"
      file_path: "src/api/jobs.py"
      
  # Frontend Component Development
  - id: "create_job_list"
    agent: "frontend_agent"
    task: "Create JobList component"
    priority: "HIGH"
    metadata:
      framework: "react"
      component_name: "JobList"
      props: ["jobs", "loading", "error"]
      
  - id: "test_job_list"
    agent: "qa_agent"
    task: "qa.frontend_validation"
    depends_on: ["create_job_list"]
    priority: "MEDIUM"
    metadata:
      test_type: "component"
      component: "JobList"
      file_path: "src/components/JobList.tsx"
      
  # Project Management Tasks
  - id: "plan_sprint"
    agent: "pm_agent"
    task: "Plan next sprint tasks"
    priority: "HIGH"
    metadata:
      sprint_duration: "2 weeks"
      team_size: 4
      
  - id: "review_progress"
    agent: "pm_agent"
    task: "Review sprint progress"
    depends_on: ["plan_sprint"]
    priority: "LOW"
    metadata:
      review_type: "daily"
      metrics: ["velocity", "burndown"]

   # Benchmark Project Analysis
  - id: "analyze_8thdegree"
    agent: "pm_agent"
    task: "Analyze benchmark 8thDegree project for breakdown"
    priority: "HIGH"
    metadata:
      source_path: "benchmark_projects/8thdegree"
      project_name: "8thDegree"
      generate_tasks: true

  - id: "analyze_8thdegree_ai"
    agent: "pm_agent"
    task: "Analyze benchmark 8thDegree-AI project for breakdown"
    priority: "HIGH"
    metadata:
      source_path: "benchmark_projects/8thdegree-ai"
      project_name: "8thDegree-AI"
      generate_tasks: true


# System-wide settings
system:
  log_level: "INFO"
  max_concurrent_tasks: 3
  task_timeout: 300  # seconds
  metrics:
    enabled: true
    retention_days: 30
    export_format: "csv"
    
# LLM Configuration
llm:
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 1000
  system_prompt: "You are a helpful AI assistant for software development."
  
# Monitoring Configuration
monitoring:
  metrics_file: "logs/metrics.csv"
  dashboard_port: 8501
  alert_thresholds:
    error_rate: 0.1
    response_time: 5000  # ms
    retry_rate: 0.2 