capabilities:
- plan_architecture
- generate_strategies
- calculate_resources
- validate_requirements
default_architecture: microservices
metadata:
  auto_generate_strategies: true
  default_deployment_type: cloud
  default_provider: aws
  default_region: us-east-1
  default_scale_factor: medium
  include_resource_calculations: true
output_dir: architecture
retry:
  backoff_strategy: exponential
  delay: 1.0
  max_delay: 32.0
  retries: 3
supported_architectures:
- microservices
- monolithic
- serverless
type: ai_architect
version:
  major: 1
  minor: 0
  patch: 0
