name: Setup Project Board

on:
  push:
    branches:
      - main
    paths:
      - '.github/project-board.yml'
      - '.github/workflows/project-board.yml'
      - '.github/scripts/setup-project-board.js'

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  setup-project-board:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install js-yaml

      - name: Setup project board
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: node .github/scripts/setup-project-board.js 