name: Sync Tasks to Project Board

on:
  push:
    branches:
      - main
    paths:
      - 'docs/Pepper_Roadmap/ROADMAP.md'
      - 'docs/Pepper_Roadmap/TECHNICAL_SPEC.md'
      - 'docs/Pepper_Roadmap/IMPLEMENTATION_PLAN.md'
      - '.github/workflows/sync-project.yml'
      - '.github/scripts/sync-project.js'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  sync-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Sync tasks to project board
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: npm run sync-project 